# Generated by Django 2.2.16 on 2022-02-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220217_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paid',
        ),
    ]
