# Generated by Django 2.2.16 on 2022-02-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220119_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='89138881111', max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
